<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>E-monitor - Espace Etudiant</title>
    <script src="../js/d3.js"></script>
    <script src="../js/jquery.min.js" charset="utf-8"></script>
		<script src="../js/jquery.blast.min.js"></script>
    <script src="../js/w2ui.js" charset="utf-8"></script>
    <link rel="stylesheet" href="../css/roue.css">
    <link rel="stylesheet" href="../css/opensans.css">
    <link rel="stylesheet" href="../css/sequences.css"/>
    <link rel="stylesheet" href="../css/w2ui-dark.css" />
    <link rel="stylesheet" href="../font/font-awesome/font-awesome.css" />
  </head>
  <body >
    
  <div class="loader"></div>
    <!-- <div id="layout" style="width: 80%; height: 720px; left:50%;margin-left:50%;"></div> -->
    <div id="layout" style="position: absolute; top: 10px; left: 10px; bottom: 10px; right: 10px;"></div>
    <script >
      
    var user = '<?php echo $this->user;?>';
    var formation = '<?php echo $this->formation;?>';
    $(function () {
        var pstyle = ' color: #000000; border: 0px solid #dfdfdf; padding: 5px; ';
        $('#layout').w2layout({
            name: 'layout',
            panels: [
                { type: 'top', size:330, style: pstyle},
                { type: 'main',  style: pstyle, content: '<div id="vis" align="center" valign="middle"></div>' },
                { type: 'bottom', style: pstyle, content: '<div class="w2ui-buttons" align="center">'+
            '<button class="w2ui-btn w2ui-btn-green" style="font-size:40px;" name="save" onclick="saveEmotion()">Enregistrer</button>'+
          '</div>' }
            ]
        });
        $().w2layout({
        name: 'layout2',
        panels: [
            { type: 'left', size: '70%',  style: pstyle, content: '<div id="text" style="float: left; font-size:40px;">'+
                  'Espace Etudiant <br>Utilisateur : '+user+
                  '<br>Formation : '+ formation+
                  '</div>' },
            { type: 'main', style: pstyle, content : '<div class="w2ui-buttons" style="float: right;" >'+
                  '<button class="w2ui-btn w2ui-btn-grey" style="font-size:40px;" name="deconnexion" onclick="disconnect()">Déconnexion</button><br><br>'+
                  '<button class="w2ui-btn w2ui-btn-grey" style="font-size:40px;float:right;" name="aide" onclick="aide()">Aide</button>'+
                  '</div>' }
            ]
    });
    
    w2ui['layout'].content('top', w2ui['layout2']);
    
    });

    function saveEmotion(){
      console.log("save emotion;");
      var json = {};
        //old code for D3 wheel
      // for (var key in selectedEmotion) {
      //   json[key] = selectedEmotion[key].data;
      // }
      for(var i = 0; i < selectedEmotion.length; i++)
	    {
        json[selectedEmotion[i].substr(0,selectedEmotion[i].length-1)] = selectedEmotion[i].substr(selectedEmotion[i].length-1);
      }
      var dt ={'emotions' : json};
      if (selectedEmotion.length == 0){
        alert("Merci de sélectionner tes émotions sur la carte.")
      }
      else{
      saveRepD3(dt);
      }
    }

    function saveRepD3(dt) {
			$.ajax({
		    		url: "saverepd3",
		    		data: dt,
		    		type: 'get',
            dataType: 'json',
            error: function(error){
              try {
                var js = JSON.parse(error.responseText);
              } catch (e) {
                console.log(error.responseText)            		  	
              w2alert("Erreur : "+e+dt);
              }
            },            	
            success: function(result) {
              // var message = "<?php echo $this->message ?>";
              saveResult = result;
              // alert (message);
              alert(result["message"]);
		        }
			});
    }
    
    function aide(){
      alert("Bienvenue dans E-monitor.\n"+
            "Dans cette application tu peux exprimer tes émotions auprès de tes enseignants pour un meilleur suivi pédagogique.\n"+
            "La saisie est possible 2 fois par jour de 9h à 14h et de 14h à 19h, du lundi au vendredi.\n"+
            "Pour exprmier ce que tu ressens durant les cours, il suffit de sélectionner une ou deux émotions sur la carte en cliquant sur l\'intensité qui correspond.");
    }

    function disconnect() {
			window.location.href="../auth/deconnexion";
		}

    function addScript(JSfileName) {
    var js = document.createElement('script');
    js.setAttribute('type', 'text/javascript');
    js.src = JSfileName;
    document.body.appendChild(js);
    }

    setTimeout(function(){
      d3.xml("../svg/carto.svg").mimeType("image/svg+xml").get(function(error, xml) {
  if (error) throw error;
	var importedNode = document.importNode(xml.documentElement, true);
  d3.select("div#vis").attr("id","svg-container")
    
    // .attr("transform", "translate( 0," +(parseInt(document.getElementById("layout_layout_panel_main").style.height,10)-623) / 2 + ")")
	  .each(function() {
	    this.appendChild(importedNode);
	  })
	  // inside of our d3.xml callback, call another function
	  // that styles individual paths inside of our imported svg
	  // styleImportedSVG()
    $('.loader').fadeOut();
});
    // d3.select(chart).style("height", "700px");
    }, 100);
    addScript('../js/carto.js');
    
    
    </script>

  </body>
</html>