<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>E-monitor - Espace Etudiant</title>
    <script src="../js/d3.js"></script>
    <script src="../js/jquery.min.js" charset="utf-8"></script>
		<script src="../js/jquery.blast.min.js"></script>
    <script src="../js/w2ui.js" charset="utf-8"></script>
    <link rel="stylesheet" href="../css/opensans.css">
    <link rel="stylesheet" href="../css/sequences.css"/>
    <link rel="stylesheet" href="../css/w2ui-dark.css" />
    <link rel="stylesheet" href="../font/font-awesome/font-awesome.css" />
  </head>
  <body >
    
  
    <!-- <div id="layout" style="width: 80%; height: 720px; left:50%;margin-left:50%;"></div> -->
    <div id="layout" style="width: 100%; height: 820px; "></div>
    <script >

    var user = '<?php echo $this->user;?>';
    $(function () {
        var pstyle = ' color: #000000; border: 1px solid #dfdfdf; padding: 5px;';
        $('#layout').w2layout({
            name: 'layout',
            panels: [
                { type: 'top', size: 100, style: pstyle, content: '<div style="float: left; font-size:30px;">Espace Etudiant '+
                  '<br>Connecté en tant que : '+ user+
                  '</div>'+
                  '<div class="w2ui-buttons" style="float: right;" >'+
                  '<button class="w2ui-btn w2ui-btn-grey" style="font-size:30px;" name="deconnexion" onclick="disconnect()">Déconnexion</button>'+
                  '</div>'},
                { type: 'main', size: 800, style: pstyle, content: '<div id="vis" style= float :center"></div>' },
                { type: 'bottom', size: 60, style: pstyle, content: '<div class="w2ui-buttons" align="center">'+
            '<button class="w2ui-btn w2ui-btn-green" style="font-size:30px;" name="save" onclick="saveEmotion()">Enregistrer</button>'+
          '</div>' }
            ]
        });
    });

    function saveEmotion(){
      console.log("save emotion;");
      var json = {};
      for (var key in selectedEmotion) {
        json[key] = selectedEmotion[key].data;
      }
      var dt ={'emotions' : json};
      saveRepD3(dt);
    }

    function saveRepD3(dt) {
			$.ajax({
		    		url: "saverepd3",
		    		data: dt,
		    		type: 'get',
            dataType: 'json',
            error: function(error){
              try {
                var js = JSON.parse(error.responseText);
              } catch (e) {
                console.log(error.responseText)            		  	
              w2alert("Erreur : "+e+dt);
              }
            },            	
            success: function(result) {
              saveResult = result;
              w2alert("Emotions enregistrées :)");
		        }
			});
    }
    
    function disconnect() {
			window.location.href="../auth/deconnexion";
		}

    function addScript(JSfileName) {
    var js = document.createElement('script');
    js.setAttribute('type', 'text/javascript');
    js.src = JSfileName;
    document.body.appendChild(js);
    }

    setTimeout(function(){
      d3.xml("../svg/carto.svg").mimeType("image/svg+xml").get(function(error, xml) {
  if (error) throw error;
	var importedNode = document.importNode(xml.documentElement, true);
	d3.select("div#vis").attr("id","svg-container")
	  .each(function() {
	    this.appendChild(importedNode);
	  })
	  // inside of our d3.xml callback, call another function
	  // that styles individual paths inside of our imported svg
	  // styleImportedSVG()
});
    // d3.select(chart).style("height", "700px");
    addScript('../js/carto.js');
    }, 100);
    </script>

  </body>
</html>