<!DOCTYPE html>
<html>
<style>

.loader {
	position: fixed;
	left: 0px;
	top: 0px;
	width: 100%;
	height: 100%;
	z-index: 9999;
	background: url('../gif/progress.gif') 50% 50% no-repeat rgb(249,249,249);
}

body {
  font: 10px sans-serif;
}

.chart { 
  background: #fff;
}

p {
  font: 12px helvetica;
}


.axis path, .axis line {
  fill: none;
  stroke: #000;
  stroke-width: 2px;
  shape-rendering: crispEdges;
}

#viz .layer {
	cursor: crosshair;
}
.tooltip {
	  /* position: absolute; */
	  width: 180px;
	  height: 100px;
	  pointer-events: none;
		background-color: hsla(0,0%,100%,.9);
		padding: 6px;
		border-radius: 5px;
		font-size: 1em;
		/* width: 180px; */
	}

	/* input {
  display: inline-block;
  float: right;
} */
.legend {
	position: absolute;
	top: 15px;
	left: 3px;
	background-color: hsla(0,0%,100%,.9);
	padding: 5px 10px 5px 10px;
	border-radius: 5px;
}
.legend .title {
	margin-bottom: 2px;
	font-weight: 900;
}
.legend .item {
	font-size: 1em;
}
.legend .swatch {
	width: 10px;
	height: 10px;
	margin-top: 3px;
	float: left;
	margin-right: 5px;
}

* {
    box-sizing: border-box;
}

/* Create two unequal columns that floats next to each other */
.column {
    float: left;
    /*padding: 10px;
    /*height: 300px; /* Should be removed. Only for demonstration */
}


}

/* Clear floats after the columns */
.row:after {
    content: "";
    display: table;
    clear: both;
}

</style>
<head>
  <meta charset="utf-8">
  <title>E-monitor - Espace Enseignant</title>
  
  <script src="../js/date_fns.min.js"></script>
  <script src="../js/d3.v4.min.js"></script>
  <script src="../js/d3-scale-chromatic.v1.min.js"></script>  
  <script src="../js/d3-legend.min.js"></script>  
  <script src="../js/jquery.min.js"></script>
  <!-- <link rel="stylesheet" type="text/css" href="../css/w2ui-dark.css" /> -->
	<link rel="stylesheet" type="text/css" href="../css/w2ui.min.css" />
  <script src="../js/w2ui.js"></script>
      

</head>

<body>
	<script type="text/javascript">
			var resultJSON = <?php echo $this->resultJSON;?>;
			var emotionsJSON = <?php echo $this->emotionsJSON;?>;
			var formations = <?php echo $this->formations;?>;
			var emos = <?php echo $this->emos;?>;
			var user = '<?php echo $this->user;?>';
			</script>
	<script src="../js/visu.js"></script>
	<div class="loader"></div>
	<div id="layout" style="position: absolute; top: 10px; left: 10px; bottom: 10px; right: 10px;"></div>

</body>
</html>