<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title><?php echo $this->titre;?></title>
  <script src="../js/d3.v4.min.js"></script>
  <script src="../js/d3-scale-chromatic.v1.min.js"></script>  
  <script src="../js/d3-legend.min.js"></script>  
  <script src="../js/jquery.min.js"></script>
  <script src="../js/w2ui.js"></script>
  <link rel="stylesheet" type="text/css" href="../css/w2ui-dark.css" />
      
  <style>
    body { margin:0 auto;}
    h1,h2,p {
      margin:0px;
    }
    svg {
	  margin-left:auto; margin-right:auto; display:block;
    }
    
    .axis {
	  font: 10px sans-serif;
		}
    
    .axis path,
	  .axis line {
	  fill: none;
	  stroke: #000;
	  shape-rendering: crispEdges;
	}
    .tooltip {
	  position: absolute;
	  width: 300px;
	  height: 35px;
	  pointer-events: none;
	}
    
  </style>
</head>

<body>
  <p>Résultat :<br></p>
  <?php echo $this->resultJSON;?>
  <br>
  <br>
  <?php echo $this->dateJSON;?>
  <br>
  <br>
  <?php echo $this->emotionsJSON;?>
  <br>
  <br>
  <?php echo $this->message;?>
  <script>
	
  </script>
</body>
</html>