<!DOCTYPE html>
<html>
<head>
    <title>Espace Administration</title>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
    <script type="text/javascript" src="http://rawgit.com/vitmalina/w2ui/master/dist/w2ui.min.js"></script>
    <link rel="stylesheet" type="text/css" href="http://rawgit.com/vitmalina/w2ui/master/dist/w2ui.min.css" />
</head>
<body>

<div id="grid" style="width: 100%; height: 400px; overflow: hidden;"></div>
<br>
<button class="w2ui-btn" onclick="var obj = w2ui['grid']; obj.show.header = !obj.show.header; w2ui['grid'].refresh();">Header</button>
<button class="w2ui-btn" onclick="var obj = w2ui['grid']; obj.show.toolbar = !obj.show.toolbar; w2ui['grid'].refresh();">Toolbar</button>
<button class="w2ui-btn" onclick="var obj = w2ui['grid']; obj.show.columnHeaders = !obj.show.columnHeaders; w2ui['grid'].refresh();">Column Headers</button>
<button class="w2ui-btn" onclick="var obj = w2ui['grid']; obj.show.footer = !obj.show.footer; w2ui['grid'].refresh();">Footer</button>
<button class="w2ui-btn" onclick="var obj = w2ui['grid']; obj.show.lineNumbers = !obj.show.lineNumbers; w2ui['grid'].refresh();">Line Numbers</button>
<button class="w2ui-btn" onclick="var obj = w2ui['grid']; obj.show.selectColumn = !obj.show.selectColumn; w2ui['grid'].refresh();">Select Column</button>
<button class="w2ui-btn" onclick="var obj = w2ui['grid']; obj.show.expandColumn = !obj.show.expandColumn; w2ui['grid'].refresh();">Expand Column</button>

<script type="text/javascript">
$(function () {
	$('#grid').w2grid({
	    name: 'grid',
	    header: 'List of Names',

	    columns: [

	    	{ field: 'etudid', caption: 'Etudid'},
	    	{ field: 'nom', caption: 'Nom'},
	    	{ field: 'prenom', caption: 'Prenom'},
	    	{ field: 'email', caption: 'Email'},
	    ],
	    records : [
    {
        "recid": "1",
        "etudid": "EID2292",
        "nom": "ALBIN",
        "prenom": "Mélina",
        "email": "melina.albin@sfr.fr"
    },
    {
        "recid": "2",
        "etudid": "EID2013",
        "nom": "ASLANOFF",
        "prenom": "Gabriel",
        "email": "gabaslan@gmail.com"
    },
    {
        "recid": "3",
        "etudid": "EID2022",
        "nom": "CANDILLE",
        "prenom": "Ophélie",
        "email": "ophelie.candille1@gmail.com"
    },
    {
        "recid": "4",
        "etudid": "EID2025",
        "nom": "CASAJUS",
        "prenom": "Gabriel",
        "email": "gaby.casajus@gmail.com"
    },
    {
        "recid": "5",
        "etudid": "EID2028",
        "nom": "CAZAUBON",
        "prenom": "Laurie",
        "email": "cazaubon.laurie@gmail.com"
    },
    {
        "recid": "6",
        "etudid": "EID2031",
        "nom": "CHRYSSOS",
        "prenom": "Elena",
        "email": "el.chryssos@gmail.com"
    },
    {
        "recid": "7",
        "etudid": "EID112",
        "nom": "CUBAYNES",
        "prenom": "Mathilde",
        "email": "mathilde.cubaynes@gmail.com"
    },
    {
        "recid": "8",
        "etudid": "EID2034",
        "nom": "DONADILLE",
        "prenom": "Manon",
        "email": "manon.donadille@gmail.com"
    },
    {
        "recid": "9",
        "etudid": "EID2037",
        "nom": "GNANAPIRAKASAM",
        "prenom": "Caroline",
        "email": "caroline.gnana@gmail.com"
    },
    {
        "recid": "10",
        "etudid": "EID2040",
        "nom": "GODARD",
        "prenom": "Bastien",
        "email": "bastien.godard@orange.fr"
    },
    {
        "recid": "11",
        "etudid": "EID2043",
        "nom": "GONZALES",
        "prenom": "Elodie",
        "email": "elodie34700@hotmail.fr"
    },
    {
        "recid": "12",
        "etudid": "EID2049",
        "nom": "GUIVARCH",
        "prenom": "Rozenn",
        "email": "rozennguivarch@hotmail.fr"
    },
    {
        "recid": "13",
        "etudid": "EID2052",
        "nom": "KERYHUEL",
        "prenom": "Aëla",
        "email": "aela.k@hotmail.fr"
    },
    {
        "recid": "14",
        "etudid": "EID142",
        "nom": "LAFAYSSE",
        "prenom": "Joddie",
        "email": "lafaysse.joddie@outlook.fr"
    },
    {
        "recid": "15",
        "etudid": "EID2307",
        "nom": "LALES",
        "prenom": "Juliette",
        "email": "juliette.lales12@gmail.com"
    },
    {
        "recid": "16",
        "etudid": "EID2055",
        "nom": "LYONNET",
        "prenom": "Elodie",
        "email": "elodie.lyonnet@wanadoo.fr"
    },
    {
        "recid": "17",
        "etudid": "EID2058",
        "nom": "MARAIS",
        "prenom": "Jeanne",
        "email": "jeanne.marais@laposte.net"
    },
    {
        "recid": "18",
        "etudid": "EID2061",
        "nom": "MINCHELLA",
        "prenom": "Laura",
        "email": "laura.minchella@homail.fr"
    },
    {
        "recid": "19",
        "etudid": "EID2064",
        "nom": "MOMPEYSSIN",
        "prenom": "Louise",
        "email": "louise.mompeyssin@outlook.com"
    },
    {
        "recid": "20",
        "etudid": "EID2067",
        "nom": "PIPET",
        "prenom": "Marylou",
        "email": "marylou.pipet@gmail.com"
    },
    {

        "recid": "21",
        "etudid": "EID2070",
        "nom": "PLASSMANN",
        "prenom": "Marion",
        "email": "plassmann.marion@gmail.com"
    },
    {
        "recid": "22",
        "etudid": "EID2073",
        "nom": "PRESTWICH",
        "prenom": "Chloë",
        "email": "chloeprestwich@yahoo.co.uk"
    },
    {
        "recid": "23",
        "etudid": "EID2076",
        "nom": "ROUYLOU",
        "prenom": "Audrey",
        "email": "audrey.rouylou@yahoo.fr"
    },
    {
        "recid": "24",
        "etudid": "EID2079",
        "nom": "SIDICARO",
        "prenom": "Tom",
        "email": "tomsidicaro@gmail.com"
    },
    {
        "recid": "25",
        "etudid": "EID2082",
        "nom": "SIROTEAU",
        "prenom": "Florian",
        "email": "f.siroteau@gmail.com"
    },
    {
        "recid": "26",
        "etudid": "EID2088",
        "nom": "SOUILLIER",
        "prenom": "Alfwold",
        "email": "valeriefelut@free.fr"
    },
    {
        "recid": "27",
        "etudid": "EID2091",
        "nom": "TERNOY",
        "prenom": "Elise",
        "email": "elise.ternoy@free.fr"
    },
    {
        "recid": "28",
        "etudid": "EID2094",
        "nom": "TERRIER",
        "prenom": "Lauren",
        "email": "terrier.lauren@gmail.com"
    },
    {
        "recid": "29",
        "etudid": "EID2097",
        "nom": "TRIBOT",
        "prenom": "Audrey",
        "email": "audrey@tribot.fr"
    },
    {
        "recid": "30",
        "etudid": "EID2100",
        "nom": "WAYOLLE",
        "prenom": "Sophie",
        "email": "sophie78126@hotmail.fr"
    }
]
});
});
</script>

<?php echo $this->resJSON; ?>

</body>
</html>