<!DOCTYPE html>
<html>
<head>
    <title>Espace Administration</title>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
    <script type="text/javascript" src="http://rawgit.com/vitmalina/w2ui/master/dist/w2ui.min.js"></script>
    <link rel="stylesheet" type="text/css" href="http://rawgit.com/vitmalina/w2ui/master/dist/w2ui.min.css" />
</head>
<body>

<div id="grid" style="width: 100%; height: 400px; overflow: hidden;"></div>
<br>
<button class="w2ui-btn" onclick="var obj = w2ui['grid']; obj.show.header = !obj.show.header; w2ui['grid'].refresh();">Header</button>
<button class="w2ui-btn" onclick="var obj = w2ui['grid']; obj.show.toolbar = !obj.show.toolbar; w2ui['grid'].refresh();">Toolbar</button>
<button class="w2ui-btn" onclick="var obj = w2ui['grid']; obj.show.columnHeaders = !obj.show.columnHeaders; w2ui['grid'].refresh();">Column Headers</button>
<button class="w2ui-btn" onclick="var obj = w2ui['grid']; obj.show.footer = !obj.show.footer; w2ui['grid'].refresh();">Footer</button>
<button class="w2ui-btn" onclick="var obj = w2ui['grid']; obj.show.lineNumbers = !obj.show.lineNumbers; w2ui['grid'].refresh();">Line Numbers</button>
<button class="w2ui-btn" onclick="var obj = w2ui['grid']; obj.show.selectColumn = !obj.show.selectColumn; w2ui['grid'].refresh();">Select Column</button>
<button class="w2ui-btn" onclick="var obj = w2ui['grid']; obj.show.expandColumn = !obj.show.expandColumn; w2ui['grid'].refresh();">Expand Column</button>

<script type="text/javascript">
$(function () {
	$('#grid').w2grid({
	    name: 'grid',
        header: 'Liste ',
        recid: 'exi_id',
        show: {
            lineNumbers     : true,
            footer          : true,
            header          : true,
            toolbar         : false,
            toolbarColumns  : false,
            toolbarSearch   : false,
            toolbarReload   : false
        }, 
        columns: [
            { field: 'nom', caption: 'Libellé', size: '30%'},
            { field: 'nait', caption: 'Date début', size: '30%'},
            { field: 'mort', caption: 'Date Fin', size: '30%'},
        ],
	    records : [{"exi_id":"83","uti_id":null,"nom":"g1L1","prenom":null,"lft":"0","rgt":"1","parent":null,"niveau":"82","maj":"2017-12-24 23:13:28","poids":null,"data":"groupe","nait":"2017-09-01","mort":null,"isni":null,"url":null},{"exi_id":"85","uti_id":null,"nom":"g1L2","prenom":null,"lft":"0","rgt":"1","parent":null,"niveau":"84","maj":"2017-12-24 23:15:05","poids":null,"data":"groupe","nait":"2017-09-01","mort":null,"isni":null,"url":null},{"exi_id":"86","uti_id":null,"nom":"g2L2","prenom":null,"lft":"0","rgt":"1","parent":null,"niveau":"84","maj":"2017-12-24 23:15:05","poids":null,"data":"groupe","nait":"2017-09-01","mort":null,"isni":null,"url":null},{"exi_id":"88","uti_id":null,"nom":"g1LP","prenom":null,"lft":"0","rgt":"1","parent":null,"niveau":"87","maj":"2017-12-24 23:15:05","poids":null,"data":"groupe","nait":"2017-09-01","mort":null,"isni":null,"url":null}]
});
});
</script>

<?php echo $this->resJSON; ?>

</body>
</html>